#!/usr/bin/env bash

if [ -z ${DF_MOD_DIR+x} ] || [ ! -d "$DF_MOD_DIR" ]; then
    echo "Required environment variable DF_MOD_DIR is empty. Sourced from outside a dotfiles script?" 1>&2
    exit 1
fi

case "$df_os" in
"macos")
    the_bash="$($df_macos_brew --prefix bash)/bin/bash"
    shells=/etc/shells
    if $df_system; then
        if ! grep "$the_bash" "$shells" >/dev/null 2>&1; then
            echo "Adding $the_bash to $shells"
            $df_run sudo sh -c "printf \"%s\\n\" \"$the_bash\" >>\"$shells\""
        fi
    fi
    if [ "$SHELL" != "$the_bash" ]; then
        if ! grep "$the_bash" "$shells" >/dev/null 2>&1; then
            df_error "Cannot set login shell: $the_bash missing from $shells"
        else
            echo "Set login shell: $the_bash"
            $df_run chsh -s "$the_bash"
        fi
    fi
    ;;
esac

case "$df_os" in
"macos")
    local_ssh_agent="com.openssh.ssh-agent-local"
    if df_macos_service_status "$local_ssh_agent"; then
        echo "Local SSH agent already enabled."
        echo "Restart manually using:"
        echo "    dotfiles services restart $local_ssh_agent"
    else
        $df_run df_macos_service_enable "$local_ssh_agent"
        echo "Local SSH agent enabled. Update current shell environment using:"
        echo "    source ~/.ssh-agent-local"
    fi
    ;;
esac
