#!/usr/bin/env bash

if [ -z ${DF_MOD_DIR+x} ] || [ ! -d "$DF_MOD_DIR" ]; then
    echo "Required environment variable DF_MOD_DIR is empty. Sourced from outside a dotfiles script?" 1>&2
    exit 1
fi

case "$df_os" in
"macos")
    the_bash="$($df_macos_brew --prefix bash)/bin/bash"
    shells=/etc/shells
    if $df_system; then
        if ! grep "$the_bash" "$shells" >/dev/null 2>&1; then
            echo "Adding $the_bash to $shells"
            $df_run sudo sh -c "printf \"%s\\n\" \"$the_bash\" >>\"$shells\""
        fi
    fi
    if [ "$SHELL" != "$the_bash" ]; then
        if ! grep "$the_bash" "$shells" >/dev/null 2>&1; then
            df_error "Cannot set login shell: $the_bash missing from $shells"
        else
            echo "Set login shell: $the_bash"
            $df_run chsh -s "$the_bash"
        fi
    fi
    ;;
esac
