(setq ebib-bib-search-dirs '()) ; '("path/one" "path/two")
(setq ebib-file-associations '()) ; '(("ext1" . "cmd1") ("ext2" . "cmd2"))
(setq ebib-file-search-dirs nil)
(setq ebib-index-display-fields '("title"))
(setq ebib-preload-bib-files '("library.bib"))
