(setq evil-default-state 'normal)
(setq evil-shift-width 4)
(setq-default evil-auto-indent t)
(setq evil-want-visual-char-semi-exclusive t)
(define-key evil-normal-state-map (kbd "TAB") 'other-window)
(define-key evil-normal-state-map (kbd "<backtab>")
  (lambda () (interactive) (other-window -1)))
(define-key evil-normal-state-map (kbd "S-<up>") 'evil-window-up)
(define-key evil-normal-state-map (kbd "S-<down>") 'evil-window-down)
(define-key evil-normal-state-map (kbd "S-<left>") 'evil-window-left)
(define-key evil-normal-state-map (kbd "S-<right>") 'evil-window-right)
(define-key evil-normal-state-map "H" 'evil-next-buffer)
(define-key evil-normal-state-map "L" 'evil-prev-buffer)
(define-key evil-motion-state-map [prior] 'evil-scroll-page-up)
(define-key evil-motion-state-map [next] 'evil-scroll-page-down)
(evil-mode 1)
