(when (and (require 'evil)
           (require 'ebib))
  (evil-set-initial-state 'ebib-entry-mode 'emacs)
  (evil-set-initial-state 'ebib-index-mode 'emacs)
  (evil-set-initial-state 'ebib-log-mode 'emacs)
  (defun ebib-multiline-evil-hook ()
    "Hook to prevent Evil from messing with Ebib's buffer
  managment. Too much duplication of evil-ex-cmds though."
    (setq-local evil-ex-commands nil)
    (evil-ex-define-cmd "wq" 'ebib-quit-multiline-edit-and-save)
    (evil-ex-define-cmd "q[uit]" 'ebib-cancel-multiline-edit)
    (evil-ex-define-cmd "w[rite]" 'ebib-save-from-multiline-edit)
    (evil-ex-define-cmd "h[elp]" 'ebib-multiline-help)
    (evil-ex-define-cmd "s[ubstitute]" 'evil-ex-substitute)
    (evil-ex-define-cmd "&" 'evil-ex-repeat-substitute)
    (evil-ex-define-cmd "&&" 'evil-ex-repeat-substitute-with-flags)
    (evil-ex-define-cmd "~" 'evil-ex-repeat-substitute-with-search)
    (evil-ex-define-cmd "~&" 'evil-ex-repeat-substitute-with-search-and-flags)
    (evil-ex-define-cmd "registers" 'evil-show-registers)
    (evil-ex-define-cmd "marks" 'evil-show-marks)
    (evil-ex-define-cmd "ju[mps]" 'evil-show-jumps)
    (evil-ex-define-cmd "noh[lsearch]" 'evil-ex-nohighlight)
    (evil-ex-define-cmd "<" 'evil-shift-left)
    (evil-ex-define-cmd ">" 'evil-shift-right)
    (evil-ex-define-cmd "=" 'evil-ex-line-number)
    (evil-ex-define-cmd "!" 'evil-shell-command)
    (evil-ex-define-cmd "@:" 'evil-ex-repeat)
    )
  (add-hook 'ebib-multiline-mode-hook 'ebib-multiline-evil-hook))
